### ISSUE TITLE
Is this published?

### ISSUE THREAD

**Issue by NullVoxPopuli** [lezer-parser/import-tree-sitter#3]
I'm wanting to create a syntax (glimmer), and augment javascript/typescript -- I've already done this for treesitter ( https://github.com/tree-sitter/tree-sitter-javascript/pull/208 ), and it would be _super stellar_, if if I could just re-use the treesitter grammars in my codemirror stuff :D

**Comment by marijnh** [comment]
No, it's not, and no, you can't. This is a tool to translate some of tree-sitters grammar notation to Lezer, but you'll need to do a *lot* of manual adjusting to the output.
